severity: LOW
description: "Only allow ingress traffic from private VPC sources and through Google Cloud load."
recommendation: "Change ingress settings to ALLOW_INTERNAL_AND_GCLB"
resource_selector:
  resource_types:
  - cloudfunctions.googleapis.com/CloudFunction
predicate:
  expression: "!resource.ingressSettings.matches('ALLOW_INTERNAL_AND_GCLB')"
custom_output:
  properties:
    - name: ingressSettings
      value_expression:
        expression: resource.ingressSettings
